name: 'b'

on:
  push:
    branch:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'build_mode'
        default: 'devel'
        type: string
        required: false


jobs:
  b:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: b
      run: |
        echo "w1"

        echo "HOME=$HOME"

        echo "exec *.sh"
        ./script/scripthome.sh

        echo "bash *.sh"
        bash ./script/scripthome.sh

        echo "sudo bash *.sh"
        sudo bash ./script/scripthome.sh


        echo "w2"

        echo "inputs.build_mode=${{ inputs.build_mode }} "
        echo "BUILD_MODE=$BUILD_MODE"
        echo $(ls ./)

        echo "bash *.sh  - ./, mkdir"

        bash ./script/makeenv.sh -e ${{ github.event_name }} -m ${{ inputs.build_mode }}
        echo 'BUILD_MODE=\$(cat ./build.artifacts/env/build_mode.env)'
        BUILD_MODE=$(cat ./build.artifacts/env/build_mode.env)
        echo "w3"
        echo "BUILD_MODE=$BUILD_MODE"
        echo $(ls ./)

        echo "*.sh  - ./, mkdir"
        echo $(ls ./)
        ./script/mkd.sh
        echo "w4"
        echo $(ls ./)


        echo "w5"
        cd /
        echo 'cd /'
        echo $(ls ./)

